name: eco_mfi
description: Infrasoft Eco LOS

version: 0.0.239
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bluetooth_serial: 0.0.5
  shared_preferences: ^0.5.6+1
  charts_flutter: ^0.8.1
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  sqflite: any
  url_launcher: ^5.4.1
  path_provider: 1.6.0
  dropdown_menu: ^1.1.0
  xml: ^3.2.0
  material_search: ^0.2.8
  flutter_pagewise: ^0.5.0
  http: '>=0.11.3+12'
  flutter_signature_pad: ^0.1.2
  permission: 0.1.2
  stack_trace: ^1.9.3
  image: 2.1.4
  flutter_cupertino_date_picker: ^0.3.0
  datetime_picker_formfield: 1.0.0
  serializable: ^0.11.1
  date_format: ^1.0.5
  modal_progress_hud: ^0.1.2
  bubble_tab_indicator: "^0.1.4"
  dio: ^1.0.13
  flutter_image_compress: 0.6.1
  image_picker: 0.6.0+15
  font_awesome_flutter: ^8.0.1
  progress_indicators: ^0.1.2
  percent_indicator: "^1.0.14"
  get_version: ^0.0.8+5
  connectivity: 0.4.1
  timeline_list: ^0.0.4
  toast: ^0.1.3
  permission_handler: 3.0.0
  flutter_circular_chart: ^0.1.0
  device_info: ^0.4.0+1
  barcode_scan: any
  geolocator: ^5.0.1
  flutter_spinkit: ^3.1.0
  flutter_map: 0.8.2
  image_cropper: ^1.0.2
  photo_view: 0.5.0
  flutter_picker: ^1.1.0
  video_player: ^0.10.2+5
  flutter_sparkline: "^0.1.0"
  flutter_staggered_grid_view: "^0.3.0"
  scoped_model: 1.0.1
  flutter_speed_dial: ^1.2.5
  google_maps_flutter: ^0.5.27+1
  syncfusion_flutter_pdf: ^18.2.48-beta
  screenshot: ^0.2.0
  open_file: ^3.0.0
  flutter_material_color_picker: ^1.0.5
  webview_flutter : any

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons: "^0.7.0"
font_awesome_flutter: ^8.0.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo/microfinance_launcher_v1.png"
flutter:
  uses-material-design: true
  assets:
    - assets/res/constant.xml
    - assets/login_contact.png
    - assets/CIF_COLORFUL.png
    - assets/create_centers.png
    - assets/group_foundation.png
    - assets/loanApplication.png
    - assets/loan_approval.png
    - assets/loanpayout.png
    - assets/village.png
    - assets/prospect_creation.png
    - assets/qr_code_scanner.png
    - assets/result.png
    - assets/signature.png
    - assets/AddImage.png
    - assets/res/constant.xml
    - assets/CGT1.png
    - assets/CGT2.png
    - assets/Syncing.png
    - assets/SmsVerification.png
    - assets/shija_display_image.jfif
    - assets/clientlogo.png
    - assets/login_logo.png
    - assets/loanUtilization.png
    - assets/speedometer.png
    - assets/aadhar.png
    - assets/only_eco.png
    - assets/Infrasoft_Footer.png
    - assets/Insurance.png
    - assets/Loan.png
    - assets/Customer360.png
    - locale/i18n_en.json
    - locale/i18n_hn.json
    - assets/background_finger_capture.png
    - assets/fpsImages/lft_hand_thumb.png
    - assets/fpsImages/lft_hand_thumb_selected.png
    - assets/fpsImages/lft_hand_ring.png
    - assets/fpsImages/lft_hand_ring_selected.png
    - assets/fpsImages/lft_hand_pinky.png
    - assets/fpsImages/lft_hand_pinky_slected.png
    - assets/fpsImages/lft_hand_middle.png
    - assets/fpsImages/lft_hand_middle_selected.png
    - assets/fpsImages/lft_hand_index.png
    - assets/fpsImages/lft_hand_index_selected.png
    - assets/fpsImages/lft_hand_thumb.png
    - assets/fpsImages/rt_hand_thumb_selected.png
    - assets/fpsImages/rt_hand_thumb.png
    - assets/fpsImages/rt_hand_ring.png
    - assets/fpsImages/rt_hand_ring_selected.png
    - assets/fpsImages/rt_hand_pinky.png
    - assets/fpsImages/rt_hand_pinky_selected.png
    - assets/fpsImages/rt_hand_middle.png
    - assets/fpsImages/rt_hand_middle_selected.png
    - assets/fpsImages/rt_hand_index.png
    - assets/fpsImages/rt_hand_index_selected.png
    - assets/fpsImages/finger_scan_logo_grey.png
    - assets/fpsImages/finger_scan_logo_green.png
    - assets/fpsImages/finger_scan_logo_black.png
    - assets/fpsImages/security_bnr_fp.gif
    - assets/fpsImages/LTHAND.jpg
    - assets/fpsImages/RTHAND.jpg
    - assets/fpsImages/agent_biometric_img.png
    - assets/lefthand.png
    - assets/righthand.png
    - assets/background_finger_capture.png
    - loan_account.png
    - savings_account.png
    - termdeposit_account.jpg
    - assets/fingerprint-scan.png
    - assets/utilityBill.png
    - assets/Document.png
    - assets/gallery.png
    - assets/cameras.png
    - assets/galleries.png
    - assets/graph7.png
    - assets/graph8.png
    - assets/report7.png
    - locale/i18n_en_Fullerton.json
    - locale/i18n_hi_Fullerton.json
    - locale/i18n_en_Wasasa.json
    - images/
    - lib/pages/timelines/DashBoardNewArchitect/ChartsDetails.json
    - locale/i18n_my_Fullerton.json
    - assets/report8.jpg
    - assets/arrowIcon.png
    - assets/mapThemes/google_maps_theme_dark.json
    - assets/mapThemes/google_maps_theme_default.json
    - assets/mapThemes/google_maps_theme_night.json
    - assets/mapThemes/google_maps_theme_aubergine.json
fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.otf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.otf

    - family: Sansation-Bold
      fonts:
        - asset: assets/fonts/Sansation-Bold.ttf

    - family: Bitter
      fonts:
        - asset: assets/fonts/Bitter-Bold.ttf
        - asset: assets/fonts/Bitter-Regular.ttf